---

- name: ZOOKEEPER DEBIAN | Installation
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zookeeper
    - zookeeperd

- name: ZOOKEEPER DEBIAN | Deploy MyId file
  copy:
    content: "{{ myid }}"
    dest: /etc/zookeeper/conf/myid
    owner: root
    group: root
    mode: 0644
  notify: Restart zookeeper

- name: ZOOKEEPER DEBIAN | Manage MyId symlink
  file:
    state: link
    src: /etc/zookeeper/conf/myid
    dest: "{{ zookeeper_dataDir }}/myid"
    owner: root
    group: root

- name: ZOOKEEPER DEBIAN | Configuration
  template:
    src: "etc/zookeeper/conf/zoo.cfg.j2"
    dest: "/etc/zookeeper/conf/zoo.cfg"
    owner: root
    group: root
    mode: 0644
  notify: Restart zookeeper
