---

- name: ZOOKEEPER | Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ zookeeper_user}}"
    group: "{{ zookeeper_group}}"
    mode: 0755
  with_items:
    - "{{ zookeeper_dataDir }}"
    - "{{ zookeeper_logDir }}"

- name: ZOOKEEPER | Manage Redhat environment
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: ZOOKEEPER | Manage Debian environment
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"
