---

- name: ZOOKEEPER REDHAT | Manage user
  import_tasks: user.yml

- name: ZOOKEEPER REDHAT | Unarchive sources
  unarchive:
    src: "{{ zookeeper_tar_url }}"
    dest: /opt
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    remote_src: yes
  args:
    creates: /opt/zookeeper-{{ zookeeper_version }}
  notify: Restart zookeeper

- name: ZOOKEEPER REDHAT | Create symlink
  file:
    state: link
    src: /opt/zookeeper-{{ zookeeper_version }}
    dest: "{{ zookeeper_path }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"

- name: ZOOKEEPER REDHAT | Manage Systemd
  template:
    src: lib/systemd/system/zookeeper.service.j2
    dest: /lib/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: 0644
  notify: Restart zookeeper

- name: ZOOKEEPER REDHAT | Deploy MyId file
  copy:
    content: "{{ myid }}"
    dest: "{{ zookeeper_path }}/conf/myid"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: 0644
  notify: Restart zookeeper

- name: ZOOKEEPER REDHAT | Configuration
  template:
    src: "etc/zookeeper/conf/zoo.cfg.j2"
    dest: "{{ zookeeper_path }}/conf/zoo.cfg"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: 0644
  notify: Restart zookeeper
