---

###
# ZOOKEEPER
###

# Version
zookeeper_version: 3.4.13

# Sources
zookeeper_tar_url: http://mirrors.ukfast.co.uk/sites/ftp.apache.org/zookeeper/zookeeper-{{ zookeeper_version }}/zookeeper-{{ zookeeper_version }}.tar.gz

# Port
zookeeper_clientPort: 2181

# Data and Log directory
zookeeper_path: /opt/zookeeper
zookeeper_dataDir: /data/zookeeper
zookeeper_logDir: /var/log/zookeeper

# User
zookeeper_group: zookeeper
zookeeper_user: zookeeper
