---

dependencies:

  - role: java

galaxy_info:
  author: wikitops
  description: Zookeper for Linux.
  company: "Wikitops"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - jessie
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
  galaxy_tags:
    - zookeeper
    - cluster
    - zookeeperd
